### ISSUE TITLE
spinner not visible

### ISSUE THREAD

**Issue by Maverick1983** [majorimi/blazor-components#107]
I add only package Majorsoft.Blazor.Components.Loading and insert this sample code for testing:

`<LoadingPage OnLoading="@SendRequest" OverlayOpacity="0" IsLoading="@loading">
	<LoadingContent>
		<i class="fa fa-spinner fa-3x fa-spin"></i>
		<h2 class="m-3">Loading...</h2>
	</LoadingContent>
</LoadingPage>`

I don't see "spinner".

VS 2022 with .Net Core 6

**Comment by majorimi** [comment]
Hi @Maverick1983,
Thank for contacting me. Code sniper looks good so it should work. But you can check the [demo app code](https://github.com/majorimi/blazor-components/blob/master/src/Majorsoft.Blazor.Components.TestApps.Common/Components/Loading.razor) for usage.

I can give you a few tips which might be the issue:
- loading component shows only when your variable `loading` is `true`
- spinner is not part of this library that is from Bootstrap/FontAwesome so you have to add these resources to your page
- check your CSS and page layout it might messing with the component CSS. You can also check page Dom in Chrome developer tools

Let me know if it still doesn't work.

**Comment by Maverick1983** [comment]
Ok. Working

**Comment by majorimi** [comment]
Ok thanks for getting back to me. Closing this.
