### ISSUE TITLE
Bootstrap 5

### ISSUE THREAD

**Issue by mxmissile** [majorimi/blazor-components#76]
Does this work with Bootstrap 5?

**Comment by majorimi** [comment]
Hi @mxmissile,
Good question. Short answer is: **YES**.

Long answer: **it depends which component are you using?** There are many components in this collection. I would say these are the categories from Bootstrap point of view:
- Some of which is not rendering UI (Timer, Storage, Logger, etc.), so no styling apply.
- Some components have "fixed look and feel" (Toggle, Tabs, Maps, etc.), but of course lots of parameters configurable (colors, width, height) and also if you put them into a Bootstrap Grid system they will use that Grid normally...
- Special categories those components which are rendering some custom content (Modal dialog, Loader, etc.) they also have a "fixed look and fell" with configurable parameters. But the content is basically plain HTML so if you wish to show a Bootstrap Grid system or something then you can do it.
- The rest is fully bootstrap compatible (Debounce inputs, Typeahead, etc.) so mostly those which are rendering a single HTML element. Also custom CSS style classes can apply to those components.

If you check the demo app it is using Bootstrap 4 (v5 is the same concept). Please check the [Demo app code.](https://github.com/majorimi/blazor-components/tree/master/demo/Majorsoft.Blazor.Components.DemoApp) and shared [Components demo pages](https://github.com/majorimi/blazor-components/tree/master/src/Majorsoft.Blazor.Components.TestApps.Common).

Index.html has: `<link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />`


And here is a short example of `TypeaheadInput` component used in Bootstrap Grid system with Row/Col and `form-control` etc.:
```
	<div class="row pb-2">
		<div class="col-12 col-lg-8 col-xl-5">
			<TypeaheadInput id="in1" class="form-control w-100" placeholder="@("Please type in at least: " + _minCharsLength + " char(s)")"
			</TypeaheadInput>
		</div>
	</div>
```

Hope this answers your question.

**Comment by majorimi** [comment]
@mxmissile what this answering your question?

**Comment by mxmissile** [comment]
Yes, thank you for reminding me.
